name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install dependencies
        # working-directory ব্যবহার করে আমরা main/src ফোল্ডারে ঢুকছি
        run: flutter pub get
        working-directory: main/src

      - name: Build APK
        run: flutter build apk --release
        working-directory: main/src

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: main/src/build/app/outputs/flutter-apk/app-release.apk
