name: Flutter Build APK

on:
  push:
    branches:
      - main  # আপনার মেইন ব্রাঞ্চের নাম অনুযায়ী চেক করুন

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install dependencies
        # যেহেতু প্রজেক্ট রুট থেকে src ফোল্ডারে আছে
        run: flutter pub get
        working-directory: src

      - name: Build APK
        run: flutter build apk --release
        working-directory: src

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: src/build/app/outputs/flutter-apk/app-release.apk
